global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.0.10:8080']

  - job_name: 'nginx-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.0.8:9113']

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.0.7:9100']

  - job_name: 'mysql-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.0.9:9104']
